In [55]:
import numpy as np
arr1d = np.array([1, 2, 3])
print(arr1d)
arr2d = np.array([[1, 2, 3], [1, 2, 3]])  # Note the outer brackets
print(arr2d)
arr3d = np.array([
    [[1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3]]
])

print(arr3d)
print(arr1d.ndim)
print(arr2d.ndim)
print(arr3d.ndim)
arr0=np.zeros((2,3))
arr1=np.ones((3,3))
print(arr0)
print(arr1)
rand=np.random.random((3,3))
print(rand)
arrid=np.eye(3)
print(arrid)
arrrange=np.arange(0,10,2)
print(arrrange)

[1 2 3]
[[1 2 3]
 [1 2 3]]
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
1
2
3
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.40538623 0.77413649 0.0727101 ]
 [0.62150415 0.33476284 0.36291254]
 [0.42153238 0.84527069 0.18476904]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [56]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(2, 3)
6
int64
2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

















In [57]:
temp_data =np.array([[26,36,45],[45,56,33]])
print(temp_data )
print(temp_data .shape)
print(temp_data .size)
print(temp_data.dtype)
print(temp_data.ndim)
import numpy as np
GH3 = np.array([21, 23, 22])
updated_temp_data = np.vstack((temp_data,GH3))
print(updated_temp_data)
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print(sensor_error_flags)
print(greenhouse_identity)




[[26 36 45]
 [45 56 33]]
(2, 3)
6
int64
2
[[26 36 45]
 [45 56 33]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
#indexing
arr=np.array([[26,36,45],[45,56,33]])
print(arr[0][1])
print(arr[1][2])

36
33


In [59]:
arr=np.array([[26,36,45],[45,56,33]])
print(arr[:1:])

[[26 36 45]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [60]:
import numpy as np

shipments = np.array([
    [50, 60, 65, 70, 75, 80, 90],  # Apples
    [40, 45, 50, 55, 60, 65, 70]   # Oranges
])
print(shipments)
# Apples = row 0, Wednesday = column 2
apples_wed = shipments[0, 2]

# Oranges = row 1, Sunday = column 6
oranges_sun = shipments[1, 6]

print("Apples on Wednesday:", apples_wed)
print("Oranges on Sunday:", oranges_sun)
print(shipments[:,:5])
print(shipments[:,5:])
print(shipments[:1,2:6])
shipments[0,-2]=100
print(shipments)




[[50 60 65 70 75 80 90]
 [40 45 50 55 60 65 70]]
Apples on Wednesday: 65
Oranges on Sunday: 70
[[50 60 65 70 75]
 [40 45 50 55 60]]
[[80 90]
 [65 70]]
[[65 70 75 80]]
[[ 50  60  65  70  75 100  90]
 [ 40  45  50  55  60  65  70]]


In [61]:
a=np.array([[1,2,2],[123,1,2]])
b=np.array([[1,12,3],[12,10,92]])
print(a+b)
print(a*b)
print(a*2)




[[  2  14   5]
 [135  11  94]]
[[   1   24    6]
 [1476   10  184]]
[[  2   4   4]
 [246   2   4]]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [62]:
x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
print(np.mod(x, y))
print(np.power(x, y))
print(np.divide(x, y))
print(np.add(x,y))
print(np.log(x))
print(np.log(x))
print(np.max(x))
print(np.std(x))
print(np.prod(x))

[0 0 0 0]
[  1   4  27 256]
[1. 1. 1. 1.]
[2 4 6 8]
[0.         0.69314718 1.09861229 1.38629436]
[0.         0.69314718 1.09861229 1.38629436]
4
1.118033988749895
24


In [64]:
import numpy as np
# -----------------------------
# 1️⃣ Create arrays (raw data)
# -----------------------------
farmA = np.array([
    [10, 12, 11],
    [9, 11, 10],
    [12, 13, 14],
    [8, 7, 9]
])

farmB = np.array([
    [20, 19, 21],
    [18, 20, 19],
    [22, 23, 21],
    [17, 18, 16]
])

farmC = np.array([
    [15, 16, 14],
    [14, 13, 15],
    [16, 17, 18],
    [12, 11, 13]
])

# Stack into one 3D array (3 farms × 4 panels × 3 hours)
production_all = np.stack([farmA, farmB, farmC])

# -----------------------------
# 2️⃣ Array attributes
# -----------------------------
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Ndim:", production_all.ndim)

# -----------------------------
# 3️⃣ Per-farm totals (sum, mean, std, var)
# -----------------------------
total_per_farm = np.sum(production_all, axis=(1, 2))
mean_per_farm = np.mean(production_all, axis=(1, 2))
std_per_farm = np.std(production_all, axis=(1, 2))
var_per_farm = np.var(production_all, axis=(1, 2))

print("\nTotal per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)

# -----------------------------
# 4️⃣ Per-hour weighted estimate
# -----------------------------
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print("\nWeighted per panel (shape):", weighted_per_panel.shape)
print(weighted_per_panel)

# ----------------------

# -----------------------------
# 6️⃣ Normalization (z-score)
# -----------------------------
normed = (production_all - mean_per_farm[:, None, None]) / std_per_farm[:, None, None]

# -----------------------------
# 7️⃣ Exponential & log family
# -----------------------------
exp_ = np.exp(normed)
expm1_ = np.expm1(normed)
log_ = np.log(np.clip(normed, 1e-6, None))
log10_ = np.log10(np.clip(normed, 1e-6, None))
log2_ = np.log2(np.clip(normed, 1e-6, None))

# -----------------------------
# 8️⃣ Trigonometric
# -----------------------------
sin_ = np.sin(normed)
cos_ = np.cos(normed)
tan_ = np.tan(normed)
arcsin_ = np.arcsin(np.clip(sin_, -1, 1))
arccos_ = np.arccos(np.clip(cos_, -1, 1))
arctan_ = np.arctan(tan_)
deg_ = np.degrees(arctan_)
rad_ = np.radians(deg_)

# -----------------------------
# 9️⃣ Rounding
# -----------------------------
round_ = np.round(normed)
floor_ = np.floor(normed)
ceil_ = np.ceil(normed)
trunc_ = np.trunc(normed)

# -----------------------------
# 🔟 Comparison & logical
# -----------------------------
high_output = production_all > 20
even_hours_mask = np.array([False, True, False])[None, None, :]
logic_and = np.logical_and(high_output, even_hours_mask)
logic_or  = np.logical_or(high_output, even_hours_mask)
logic_not = np.logical_not(high_output)
logic_xor = np.logical_xor(high_output, even_hours_mask)

ge_ = np.greater_equal(production_all, 20)
lt_ = np.less(production_all, 15)

# -----------------------------
# 11️⃣ Bitwise
# -----------------------------
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],  # Farm A
    [[1,1,0],[0,1,1],[1,0,0],[1,1,1]],  # Farm B
    [[0,1,1],[1,1,0],[0,0,1],[1,0,1]]   # Farm C
], dtype=int)

bit_and = np.bitwise_and(alerts, (production_all.astype(int) % 2))
bit_or  = np.bitwise_or(alerts, (production_all.astype(int) % 2))
bit_not = np.invert(alerts)

# -----------------------------
# 12️⃣ Arithmetic ufuncs
# -----------------------------
add_ = np.add(normed, 2)
sub_ = np.subtract(normed, 1)
mul_ = np.multiply(normed, 3)
div_ = np.divide(normed, 2)
pow_ = np.power(normed, 2)
mod_ = np.mod(np.abs(normed*10).astype(int), 4)

# -----------------------------
# 13️⃣ Aggregations on ufunc outputs
# -----------------------------
sum_exp = np.sum(exp_)
mean_sin = np.mean(sin_)

# -----------------------------
# 14️⃣ Broadcast-based summary table
# -----------------------------
panel_totals_per_farm = np.sum(production_all, axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
min_per_farm = np.min(panel_totals_per_farm, axis=1)
max_per_farm = np.max(panel_totals_per_farm, axis=1)

# -----------------------------
# 15️⃣ Final KPIs
# -----------------------------
overall_total = np.sum(production_all)
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=(0, 2))

# -----------------------------
# ✅ Print summary
# -----------------------------
print("\n=== Final KPIs ===")
print("Overall total:", overall_total)
print("Peak value:", peak_value, "at farm/panel/hour indices", peak_index)
print("Average per panel:", average_per_panel)
print("Needs maintenance:", needs_maintenance)
print("Sum of exp(normed):", sum_exp)
print("Mean of sin(normed):", mean_sin)


Shape: (3, 4, 3)
Size: 36
Dtype: int64
Ndim: 3

Total per farm: [126 234 174]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Var per farm: [3.91666667 3.91666667 3.91666667]

Weighted per panel (shape): (3, 4)
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]

=== Final KPIs ===
Overall total: 534
Peak value: 23 at farm/panel/hour indices (np.int64(1), np.int64(2), np.int64(1))
Average per panel: [15.33333333 14.33333333 17.33333333 12.33333333]
Needs maintenance: [ True False  True]
Sum of exp(normed): 57.55695815214101
Mean of sin(normed): 6.1679056923619804e-18


In [76]:
arr=np.array([1,2,3,4,5,65])
arr1=np.array([1,2,3,4,5,6])

print(np.vstack((arr,arr1)))
print(np.hstack((arr,arr1)))
print(np.array_split(arr,3))

[[ 1  2  3  4  5 65]
 [ 1  2  3  4  5  6]]
[ 1  2  3  4  5 65  1  2  3  4  5  6]
[array([1, 2]), array([3, 4]), array([ 5, 65])]


In [77]:
arr=np.array([1,2,3,4,5,65])
print(arr[arr>3])
indexs=[1,2]
print(arr[indexs])

[ 4  5 65]
[2 3]


In [78]:
arr=np.array([1,2,3,4,5,65])
view=arr.view()
view[0]=10
copy=arr.copy()
copy[2]=10
print(view,"\n",copy)

[10  2  3  4  5 65] 
 [10  2 10  4  5 65]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [98]:
arr = np.arange(10, 51)
arr1=np.random.random((3,3))
print(arr)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
arr1=arr1+5
print(arr1)
print(arr1)
arr2d = np.array([[1, 2, 3], [1, 2, 3]])  # Note the outer brackets
arr2d1 = np.array([[1,12, 0], [1, 0, 5]])  # Note the outer brackets
print(arr2d*arr2d1)
arr12 = np.arange(1, 26).reshape(5,5)
print(arr12[0,:])
print(arr12[ :,4])
print(arr12[:3,:2])
arr23 = np.random.randint(10, 101, size=10)
print("Array:", arr23)
print(np.max(arr23))
print(np.min(arr23))
print(np.mean(arr23))
print(np.std(arr23))
#Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
arr24=np.arange(1,13).reshape(3,4)
print(arr24)
arrones=np.ones((3,3))
mat1=np.array([1, 2, 3])
print(arrones+mat1)
arr26 = np.random.randint(1, 51, size=10)
print( arr26[arr26 % 5 == 0])
import numpy as np

# Create two 2x2 matrices
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(np.dot(A, B))
arr = np.arange(1, 17).reshape(4, 4)
print( arr[[0, 1, 2, 3], [0, 1, 2, 3]])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
(3, 3)
9
float64
[[5.42593253 5.24266919 5.44036475]
 [5.76268376 5.20385607 5.9400038 ]
 [5.58107328 5.71885209 5.75991653]]
[[5.42593253 5.24266919 5.44036475]
 [5.76268376 5.20385607 5.9400038 ]
 [5.58107328 5.71885209 5.75991653]]
[[ 1 24  0]
 [ 1  0 15]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
Array: [85 78 53 70 16 71 18 91 64 21]
91
16
56.7
27.033497738916434
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[10 50]
[[19 22]
 [43 50]]
[ 1  6 11 16]
